In [96]:
#importing required python libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import asn1tools

In [97]:
#loading the .jsonl log files
df_q40_decoded = pd.read_json("/Users/eagmurray/Projects/DataAnalysis/Q40/18March/Q40_1718March/decoded_log.jsonl",lines=True)
df_m10_decoded = pd.read_json("/Users/eagmurray/Projects/DataAnalysis/Q40/18March/M10_1718March/decoded_log.jsonl",lines=True)

In [98]:
#converting times to date-time for plotting
df_m10_decoded["ts"] = pd.to_datetime(df_m10_decoded["ts"])
df_q40_decoded["ts"] = pd.to_datetime(df_q40_decoded["ts"])

In [99]:
print(df_q40_decoded.columns)

Index(['ts', 'tow', 'year', 'month', 'day', 'hour', 'minute', 'second', 'lat',
       'lon', 'alt', 'hgt', 've', 'vn', 'vu', 'fixStatus', 'DoP',
       'horizPosError', 'vertPosError', 'horizVelError', 'vertVelError',
       'timeRateError', 'sats', 'services'],
      dtype='str')


In [100]:
df_q40_decoded["lat"][3]

np.float64(50.438825549127614)

In [101]:
delta_lat = df_q40_decoded["lat"]-df_q40_decoded["lat"][0]
delta_lon = df_q40_decoded["lon"]-df_q40_decoded["lon"][0]

In [102]:
df_q40_decoded["DoP"][0]

{'horizontalDilutionOfPrecision': 65,
 'verticalDilutionOfPrecision': 45,
 'geometricDilutionOfPrecision': 104,
 'timeDilutionOfPrecision': 68,
 'positionDilutionOfPrecision': 79,
 'wordPadding': 0}

In [110]:
hDOP=np.zeros(len(df_q40_decoded))
vDOP=np.zeros(len(df_q40_decoded))
gDOP=np.zeros(len(df_q40_decoded))
tDOP=np.zeros(len(df_q40_decoded))
pDOP=np.zeros(len(df_q40_decoded))

for i in range(len(df_q40_decoded)):
    hDOP[i] = df_q40_decoded["DoP"][i]["horizontalDilutionOfPrecision"]
    vDOP[i] = df_q40_decoded["DoP"][i]["verticalDilutionOfPrecision"]
    gDOP[i] = df_q40_decoded["DoP"][i]["geometricDilutionOfPrecision"]
    tDOP[i] = df_q40_decoded["DoP"][i]["timeDilutionOfPrecision"]
    pDOP[i] = df_q40_decoded["DoP"][i]["positionDilutionOfPrecision"]

In [119]:
lat_pdop_cov = np.cov(delta_lat,pDOP)
lat_hdop_cov = np.cov(delta_lat,hDOP)
lat_vdop_cov = np.cov(delta_lat,vDOP)
lat_gdop_cov = np.cov(delta_lat,gDOP)
lat_tdop_cov = np.cov(delta_lat,tDOP)

lon_pdop_cov = np.cov(delta_lon,pDOP)
lon_hdop_cov = np.cov(delta_lon,hDOP)
lon_vdop_cov = np.cov(delta_lon,vDOP)
lon_gdop_cov = np.cov(delta_lon,gDOP)
lon_tdop_cov = np.cov(delta_lon,tDOP)

In [129]:
print(f"{lat_pdop_cov}\n")
print(f"{lat_hdop_cov}\n")
print(f"{lat_vdop_cov}\n")
print(f"{lat_gdop_cov}\n")
print(f"{lat_tdop_cov}\n")

print(f"{lon_pdop_cov}\n")
print(f"{lon_hdop_cov}\n")
print(f"{lon_vdop_cov}\n")
print(f"{lon_gdop_cov}\n")
print(f"{lon_tdop_cov}\n")

[[   9.78683684   14.64277029]
 [  14.64277029 7591.45619984]]

[[   9.78683684   11.42242444]
 [  11.42242444 6994.04195336]]

[[   9.78683684   11.69602935]
 [  11.69602935 7076.5082236 ]]

[[   9.78683684   16.66891196]
 [  16.66891196 7876.19157244]]

[[   9.78683684   11.58458273]
 [  11.58458273 6906.25821986]]

[[9.71413991e+00 1.43038489e+00]
 [1.43038489e+00 7.59145620e+03]]

[[ 9.71413991e+00 -1.22365055e+00]
 [-1.22365055e+00  6.99404195e+03]]

[[ 9.71413991e+00 -1.00093008e+00]
 [-1.00093008e+00  7.07650822e+03]]

[[9.71413991e+00 3.10117312e+00]
 [3.10117312e+00 7.87619157e+03]]

[[ 9.71413991e+00 -1.09071099e+00]
 [-1.09071099e+00  6.90625822e+03]]

